### ISSUE TITLE
Creating payment with customers.

### ISSUE THREAD

**Issue by guidotajan** [mercadopago/px-nodejs#63]
The ID of every customer is a String value. This causes an error everytime someone tries to make a payment with customers because the field "payer.id" requieres an Integer. Although if you put that String in the same field and send the request manually via a HTTP REST client, the payment is processed perfectly.

The error recibed is this one: 
`Error: The next fields are failing n validation: ".payer.id": should be integer.
     at Object.requestManager.buildRequest (/app/node_modules/mercadopago/lib/request-manager.js:270:17)
     at Object.<anonymous> (/app/node_modules/mercadopago/lib/request-manager.js:302:18)
     at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:300:9)
     at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:481:18)
     at new Promise (/app/node_modules/bluebird/js/release/promise.js:77:14)
     at Object.requestManager.exec (/app/node_modules/mercadopago/lib/request-manager.js:296:10)
     at /app/node_modules/mercadopago/lib/request-manager.js:106:31
     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:510:31)
     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:567:18)
     at Promise._settlePromiseCtx (/app/node_modules/bluebird/js/release/promise.js:604:10)
     at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:138:12)
     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
     at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
     at runCallback (timers.js:649:20)
     at tryOnImmediate (timers.js:622:5)`

**Comment by arielfr** [comment]
Thanks @guidotajan , the problem is solved. This package is in beta yet, but, use it!, this is the most updated SDK for NodeJS.

If you are using this dependency referencing the Repository on the package.json remove the node_modules/mercadopago and do a "npm i" again.

The NodeJS SDK validates the JSON before sending it, that's was the issue. If you encounter any problem like this, please, open another issue and we will fix it 👍
