### ISSUE TITLE
TypeError: this.exec is not a function

### ISSUE THREAD

**Issue by Rart3001** [mercadopago/px-nodejs#71]
I am trying to execute the following code:

```
const mercadopago = require('mercadopago');

exports.handler = function(userId, authorizationCode, req, res) {

  console.log(`Requesting credentials with the token = ${authorizationCode}`);

  mercadopago.configure({sandbox: true, access_token: ACCESS_TOKEN});
  mercadopago.connect.getCredentials(ACCESS_TOKEN, authorizationCode, (MP_URL + userId)).then((result) => {

    console.log(`result = ${result}`);
    

  }).catch((error) => {
    console.log(error);
  });

}
```

But it always gives me the same error:

```
TypeError: this.exec is not a function
    at Object.<anonymous> (/user_code/node_modules/mercadopago/lib/request-manager.js:220:17)
    at Promise._execute (/user_code/node_modules/mercadopago/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/user_code/node_modules/mercadopago/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/user_code/node_modules/mercadopago/node_modules/bluebird/js/release/promise.js:79:10)
    at Object.requestManager.getUserCredentials [as getCredentials] (/user_code/node_modules/mercadopago/lib/request-manager.js:219:10)
```

**Comment by arielfr** [comment]
@Rart3001 Thanks for the report, sorry for the delay. Bug Fixed. Can you please update npm dependency and check again?
